% Author: Eduardo Peixoto
% E-mail: eduardopeixoto@ieee.org
function dec = getDecoder()

dec = struct('params',getEncoderParams(),...
             'pointCloud',[],...
             'geometryCube',[],...
             'dimensionSliced','',...
             'pcLimit',0,...
             'numberOfOccupiedVoxels',0,...
             'rate',0,...
             'rate_bpov',0,...
             'cabac',[]);
                    