% Author: Eduardo Peixoto
% E-mail: eduardopeixoto@ieee.org
function cabac = getCABAC()

cabac = struct('BACParams',[],...
               'BACEngine',[],...
               'BACEngineDecoder',[],...
               'BACContexts_2D_Independent',[],...
               'BACContexts_2D_Masked',[],...
               'BACContexts_3D',[],...
               'BACContexts_3D_ORImages',[],...
               'ParamBitstream',[]);